#------------------------------
# ENVIRONMENT
#------------------------------

# days and number of experiments for each experiment
exp_values:
  exp3:
    days: 365
    n_exp: 100
    n_people: 850
  exp4:
    days: 365
    n_exp: 10
    n_people: 850
  exp5:
    days: 365
    n_exp: 10
    delay: 30
  exp6:
    days: 365
    n_exp: 10
    delay: 30
  exp7:
    days: 365
    n_exp: 10
    delay: 30

avg_price: 6 # avg price of a beer
avg_cc: 0.42 # avg cost per click

prices: [2, 3, 4, 5.5, 6, 6.5, 7, 8, 10, 12]
bids: [.30, .34, .38, .40, .42, .44, .46, .48, .50, .52]  

num_people: 52000

# how class are identified
# labels | class | report
# [Y, I] | 0     | C1
# [Y, D] | 1     | C1
# [A, I] | 2     | C2
# [A, D] | 3     | C3
#
#  | Y | A |
# I|C1 |C2 |
# D|C1 |C3 |

conv_rates:

- [.10, .25, .60, .25, .19, .18, .09, .05, .01, .00] # C1
- [.10, .25, .60, .25, .19, .18, .09, .05, .01, .00] # C1
- [.01, .04, .09, .10, .25, .28, .34, .46, .28, .15] # C2
- [.05, .12, .16, .20, .45, .35, .30, .20, .12, .09] # C3

cost_per_click: [
  0.32, # C1
  0.32, # C1
  0.55, # C2
  0.44  # C3
]

return_probability: [
  0.5,  # C1
  0.5,  # C1 
  4.43, # C2 
  1     # C3
]

new_clicks: [
  0.05, # C1
  0.05, # C1
  0.02, # C2
  0.01  # C3
]

class_distribution: [
  0.05, # C1
  0.24, # C1
  0.28, # C2
  0.43  # C3
]

features: # labels
  - ["Y", "A"]
  - ["I", "D"]

#------------------------------
# GENERAL
#------------------------------
seed: 1234
env_imgpath: "img/environment"
exp_imgpath: "img/experiments"
colors: ['#EF476F', '#FFD166', '#06D6A0', '#118AB2', '#008000']
class_colors: ['r', 'g', 'b', 'y']
class_labels: [
  "(C1) young - int/disint", 
  "(C1) young - disinterested", 
  "(C2) adult - interested", 
  "(C3) adult - disinterested" 
]