seed: 1234
imgpath: "img"

params:
  avg_price: 6
  avg_cc: 0.42 # avg cost per click
  prices: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  bids: [.42, .43, .5, .6]

feature1: ["young", "adult"]
feature2: ["interested", "disinterested"]

conv_rate:
  young:
    interested: [1.26, 0.6]
    disinterested: [1.44, 1.04]
  adult:
    interested: [2.17, 0.86]
    disinterested: [0.53, 0.3]
  
features_colors:
  young:
    interested: 'r'
    disinterested: 'g'
  adult:
    interested: 'b'
    disinterested: 'y'
