seed: 1234


params:
  avg_price: 7
  avg_cc: 0.42 # avg cost per click
  prices: [2, 3, 5, 6, 7, 8, 10, 11, 12, 13]
  bids: [.42, .43, .5, .6]
  days: 365
  num_classes: 3

  conv_rate:
    class1: 
      a: 1
      b: 2
    class2:
      a: 1
      b: 2
    class3:
      a: 1
      b: 2

  click_through_rate: 0.01
  prova:
    - uno:
        a: 2
        b: 3
    - due:
        a: 2
        b: 3

subcampaign1:
  prices: [0000]

